language: node_js
node_js:
- node
- '8'
before_deploy: npm run build
deploy:
  provider: pages
  fqdn: lomaji.ithuan.tw
  skip_cleanup: true
  local_dir: build/
  github_token:
    secure: DUN6YtqCkWLeOAGpYTgxic92obLf/0XsVweCkYfaEKQNd+ximdVOkVj/dbsBr0F08k7iufTj5MhKIltz7xUXsSLbgn0Tw0LQbw/DCgw0YkAdVX01berBrhy2e9qpN5wDukmwBhzsg9sBSpNL+TQBC8j826nHQRIE6vs9ZWJ5T+WhJJYJkcQQ3M/hUnGQgnWjR8fqt5uZSNKQYkTAlCNE4ygkR5uOzHRy7QuOSnV8isYi6r+ju+Fkx31bGAAJcYsyLYpz21LxuDkXEK9oVAJzPhgaOIHk8+NGlP6/LD19kyh5Pyew63K3x5rUJyCnrHfoUhgurIjTXOmYnyTrtr2dktHKmTMDxbNZffZ1+8+cbgDzCsPlqborFqlTyyKe3Pn9WLianyVvkGP1w/wG4+UYVbL7nh7TO38FWq0FwXZH8nG+gEjT2V99Drg/g7+mygSnGwhJqF3QNzCFmtuUlgelfpzeYP69r0gm8XhjrAHcpLeGmvmXoO2nXpDySQo1EylKYFHMWx2O0FKkQ+Hr1WnWBuoOZRQGSYtLvLKKp1jUSG5h2qtFzz0wVy+tNVq/YBDZGBrZ3OW34oH4rqtpvNDHmspJz9x4kAOWJc5YNxFKuivGMvlBCt8JS6APzLCgWjzxHAFcAbQDHyADpg9HefUapqMOO2RroccWVaNFlmFnjHw=
  on:
    branch: master