language: node_js
node_js:
- node
- '8'
before_deploy: npm run build
deploy:
  provider: pages
  fqdn: lomaji.ithuan.tw
  skip_cleanup: true
  local_dir: build/
  github_token:
    secure: kULTntPyJy37lT15eH6xgC9RFHzHklgXkxkpzjEY4GzJPOzZmo11FyD4uMZ4Am/8GPtsoe9LWN74Ht8O+V+Gq1FFawTa/u4gJMjirhL9YxoAoaemPGfW68/bCt7y7RNeArQks8b9Jno7/TQfr9p3VhhMBVEGlcS8pMWY7BjpRWXMCsY6xkQfumP+c+luQouuPlSV8mrhmW39XDp47IlThUbJVukoCVWM/sZxpAQRUSce7VfkEfss/bO9HsGctHNN/A+pXtCRYd3F0KhGP1rjad/pEwCXWVTkn/o2GCgnFTeazxgUHO0fxPIISHC5qyrufTHBSZpyrOJiqZ4nqecPIWWOBf2gUV3F2J9BYm4RgtG8w+HCnsndathVm5KHe1mhCjACoLpfA6oCLq4sPJbete7eHd8iBmlm8UiCE1pG5Y7P8jVPzwl6xykNpY0/epLOC6ryud3jX2m/pJcHheGA1SQXFM8hcSIQZ3IPLa7k5j3/LX1FqP7AqElHoVj5JIfk/WfCEF5zQpUnF9kqZDPzKaOqcptMB4XmFJyt1Z0Jb9vDMhlaiU+OnJMO2ypc1R056GfnvTNjG0ViPQa3rFdgGpG2pNgwjxhbeq6lLyVW4J8yj2m1woDGTizVsyBaNVuZILZpAaW1Afq5ZYy0xJNjcp4ifK+j/lRY4kvsbHjWSXQ=
  on:
    branch: master
